waypoints:
  - {x: 1.5, y: 0.0, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 1.8, y: -1.0, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 1.8, y: -1.0, z: 1.0, yaw: -1.57, flag: 1}
  - {x: 1.8, y: -1.0, z: 1.0, yaw: -1.3, flag: 1}
  - {x: 1.8, y: -1.0, z: 1.0, yaw: -1.57, flag: 1}
  - {x: 1.8, y: -1.0, z: 1.0, yaw: -1.3, flag: 1}
  - {x: 1.5, y: 0.0, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 1.5, y: 0.0, z: 1.0, yaw: 0.0, flag: 2}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 0.0, flag: 0}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 1.8, flag: 1}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 1.8, flag: 1}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 1.57, flag: 1}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 1.2, flag: 1}
  - {x: 2.0, y: 1.5, z: 1.0, yaw: 0.0, flag: 2}